/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: EFOxx5rYzf2xkA0R5ZomHy2Vo+aj1zteoOlsYH/g1kRl2FeC0bn0LU+CxoJCh2e9Uf83SiNAsA2ZHOtRky3x3A==
 */

/* eslint-disable */
// tslint:disable

type HookType = 'onBranchMerge' | 'onPullRequest' | 'onPullRequestClose';
export type {HookType}
