/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Ew139Q1LJtM0+Gg3+/5VPyrsjRJmMk0/vgTngcf118rEk7qMjz/ElsAwEN0V3q2LhhL3wr5YRv9eRiFqwzL9Lg==
 */

/* eslint-disable */
// tslint:disable

import {HookType} from './_enums'

interface GhaWorkflowRuns {
  check_run_id: (number) | null
  conclusion: (string) | null
  head_sha: string
  hook: HookType
  /**
   * @default nextval('gha_workflow_runs_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'gha_workflow_runs_id'}
  merge_commit_sha: string
  name: string
  pipeline_run_name: string
  pr_check_id: (number) | null
  pr_conclusion: (string) | null
  pr_number: number
  status: (string) | null
  workflow_job_id: (number) | null
  workflow_run_id: (number) | null
  workflow_run_inputs: (any) | null
  workflow_run_url: (string) | null
}
export default GhaWorkflowRuns;

interface GhaWorkflowRuns_InsertParameters {
  check_run_id?: (number) | null
  conclusion?: (string) | null
  head_sha: string
  hook: HookType
  /**
   * @default nextval('gha_workflow_runs_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'gha_workflow_runs_id'}
  merge_commit_sha: string
  name: string
  pipeline_run_name: string
  pr_check_id?: (number) | null
  pr_conclusion?: (string) | null
  pr_number: number
  status?: (string) | null
  workflow_job_id?: (number) | null
  workflow_run_id?: (number) | null
  workflow_run_inputs?: (any) | null
  workflow_run_url?: (string) | null
}
export type {GhaWorkflowRuns_InsertParameters}
