/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /OMGXqa6spFfTBQaFuJv8Rt4X4DVpXg6F3pj9DdigX/bVvFt0eiQ5BLY2cm6qHhiSEYqbZUV8DrM4zdQ8ATvAQ==
 */

/* eslint-disable */
// tslint:disable

import {HookType} from './_enums'

interface GhaHooks {
  destination_branch_matcher: (string) | null
  file_changes_matcher: string
  hook: HookType
  hook_name: string
  /**
   * @default nextval('gha_hooks_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'gha_hooks_id'}
  pipeline_name: string
  pipeline_params: any
  pipeline_ref: (string) | null
  pipeline_unique_prefix: string
  repo_full_name: string
  shared_params: (any) | null
}
export default GhaHooks;

interface GhaHooks_InsertParameters {
  destination_branch_matcher?: (string) | null
  file_changes_matcher: string
  hook: HookType
  hook_name: string
  /**
   * @default nextval('gha_hooks_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'gha_hooks_id'}
  pipeline_name: string
  pipeline_params: any
  pipeline_ref?: (string) | null
  pipeline_unique_prefix: string
  repo_full_name: string
  shared_params?: (any) | null
}
export type {GhaHooks_InsertParameters}
