/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: d0Byjr9lEb2m7GN1X0XCfUQr42JamnIRfNltMhyJHDVHNDghhFIABKzafNu9/jobBD51hjNxEH/KX1uS5z+nwA==
 */

/* eslint-disable */
// tslint:disable

import {HookType} from './_enums.js'

interface GhaWorkflowRuns {
  check_run_id: (number) | null
  conclusion: (string) | null
  head_sha: string
  hook: HookType
  /**
   * @default nextval('gha_workflow_runs_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'gha_workflow_runs_id'}
  merge_commit_sha: string
  name: string
  pipeline_run_name: string
  pr_check_id: (number) | null
  pr_conclusion: (string) | null
  pr_number: number
  repo_full_name: (string) | null
  status: (string) | null
  workflow_job_id: (number) | null
  workflow_run_id: (number) | null
  workflow_run_inputs: (any) | null
  workflow_run_url: (string) | null
}
export default GhaWorkflowRuns;

interface GhaWorkflowRuns_InsertParameters {
  check_run_id?: (number) | null
  conclusion?: (string) | null
  head_sha: string
  hook: HookType
  /**
   * @default nextval('gha_workflow_runs_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'gha_workflow_runs_id'}
  merge_commit_sha: string
  name: string
  pipeline_run_name: string
  pr_check_id?: (number) | null
  pr_conclusion?: (string) | null
  pr_number: number
  repo_full_name?: (string) | null
  status?: (string) | null
  workflow_job_id?: (number) | null
  workflow_run_id?: (number) | null
  workflow_run_inputs?: (any) | null
  workflow_run_url?: (string) | null
}
export type {GhaWorkflowRuns_InsertParameters}
