/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jhqBLgJroiuBskYfDfaTX/828Ji/xu6G6x5e0ckMxONLl5Ygm+DpTkqaJ0XTbhg1TFa7gN19BCWLBM/B5f8ClA==
 */

/* eslint-disable */
// tslint:disable

import {HookType} from './_enums.js'

interface GhaHooks {
  branch: string
  destination_branch_matcher: (string) | null
  file_changes_matcher: string
  hook: HookType
  hook_name: string
  /**
   * @default nextval('gha_hooks_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'gha_hooks_id'}
  path_to_gha_yaml: (string) | null
  pipeline_name: string
  pipeline_params: any
  pipeline_ref: (string) | null
  pipeline_unique_prefix: string
  repo_full_name: string
  shared_params: (any) | null
  slash_command: (string) | null
}
export default GhaHooks;

interface GhaHooks_InsertParameters {
  branch: string
  destination_branch_matcher?: (string) | null
  file_changes_matcher: string
  hook: HookType
  hook_name: string
  /**
   * @default nextval('gha_hooks_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'gha_hooks_id'}
  path_to_gha_yaml?: (string) | null
  pipeline_name: string
  pipeline_params: any
  pipeline_ref?: (string) | null
  pipeline_unique_prefix: string
  repo_full_name: string
  shared_params?: (any) | null
  slash_command?: (string) | null
}
export type {GhaHooks_InsertParameters}
