/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: x5vU9PyWQZOWwg1cM4uxcUW6HxeySlgkkHBzJn7cfcdjsmCEBfZ295z/3sjqbC6iUW1CgY2KUumUQONE2k0bdA==
 */

/* eslint-disable */
// tslint:disable

import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import GhaHooks, {GhaHooks_InsertParameters} from './gha_hooks'

interface DatabaseSchema {
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  gha_hooks: {record: GhaHooks, insert: GhaHooks_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "gha_hooks" && c === "pipeline_params") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  GhaHooks,
  GhaHooks_InsertParameters,
}
